[tool.poetry]
name = "llama-index-examples"
version = "0.1.0"
description = ""
authors = ["Auth0 <support@auth0.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.scripts]
start = "scripts.start:main"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.1.1"
fastapi = "^0.115.14"
requests = "^2.32.4"
hypercorn = "^0.17.3"
llama-index = "^0.14"
auth0-fastapi = "1.0.0b5"
auth0-ai-llamaindex = { path = "../../../packages/auth0-ai-llamaindex", develop = true }
slack-sdk = "^3.36.0"
pygithub = "^2.6.1"
itsdangerous = "^2.2.0"
jinja2 = "^3.1.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
